// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221230044210_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for ptoduct 1",
                            Name = "Product 1",
                            Price = 907m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for ptoduct 2",
                            Name = "Product 2",
                            Price = 905m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for ptoduct 3",
                            Name = "Product 3",
                            Price = 276m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for ptoduct 4",
                            Name = "Product 4",
                            Price = 387m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for ptoduct 5",
                            Name = "Product 5",
                            Price = 351m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for ptoduct 6",
                            Name = "Product 6",
                            Price = 511m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for ptoduct 7",
                            Name = "Product 7",
                            Price = 162m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for ptoduct 8",
                            Name = "Product 8",
                            Price = 758m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for ptoduct 9",
                            Name = "Product 9",
                            Price = 136m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for ptoduct 10",
                            Name = "Product 10",
                            Price = 281m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for ptoduct 11",
                            Name = "Product 11",
                            Price = 722m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for ptoduct 12",
                            Name = "Product 12",
                            Price = 490m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for ptoduct 13",
                            Name = "Product 13",
                            Price = 884m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for ptoduct 14",
                            Name = "Product 14",
                            Price = 782m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for ptoduct 15",
                            Name = "Product 15",
                            Price = 293m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for ptoduct 16",
                            Name = "Product 16",
                            Price = 735m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for ptoduct 17",
                            Name = "Product 17",
                            Price = 205m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for ptoduct 18",
                            Name = "Product 18",
                            Price = 845m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for ptoduct 19",
                            Name = "Product 19",
                            Price = 431m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for ptoduct 20",
                            Name = "Product 20",
                            Price = 947m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for ptoduct 21",
                            Name = "Product 21",
                            Price = 230m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for ptoduct 22",
                            Name = "Product 22",
                            Price = 731m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for ptoduct 23",
                            Name = "Product 23",
                            Price = 548m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for ptoduct 24",
                            Name = "Product 24",
                            Price = 439m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for ptoduct 25",
                            Name = "Product 25",
                            Price = 367m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for ptoduct 26",
                            Name = "Product 26",
                            Price = 365m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for ptoduct 27",
                            Name = "Product 27",
                            Price = 264m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for ptoduct 28",
                            Name = "Product 28",
                            Price = 981m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for ptoduct 29",
                            Name = "Product 29",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for ptoduct 30",
                            Name = "Product 30",
                            Price = 887m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for ptoduct 31",
                            Name = "Product 31",
                            Price = 687m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for ptoduct 32",
                            Name = "Product 32",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for ptoduct 33",
                            Name = "Product 33",
                            Price = 191m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for ptoduct 34",
                            Name = "Product 34",
                            Price = 188m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for ptoduct 35",
                            Name = "Product 35",
                            Price = 282m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for ptoduct 36",
                            Name = "Product 36",
                            Price = 622m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for ptoduct 37",
                            Name = "Product 37",
                            Price = 863m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for ptoduct 38",
                            Name = "Product 38",
                            Price = 600m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for ptoduct 39",
                            Name = "Product 39",
                            Price = 638m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for ptoduct 40",
                            Name = "Product 40",
                            Price = 566m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for ptoduct 41",
                            Name = "Product 41",
                            Price = 581m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for ptoduct 42",
                            Name = "Product 42",
                            Price = 646m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for ptoduct 43",
                            Name = "Product 43",
                            Price = 279m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for ptoduct 44",
                            Name = "Product 44",
                            Price = 958m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for ptoduct 45",
                            Name = "Product 45",
                            Price = 393m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for ptoduct 46",
                            Name = "Product 46",
                            Price = 433m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for ptoduct 47",
                            Name = "Product 47",
                            Price = 795m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for ptoduct 48",
                            Name = "Product 48",
                            Price = 128m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for ptoduct 49",
                            Name = "Product 49",
                            Price = 848m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for ptoduct 50",
                            Name = "Product 50",
                            Price = 683m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for ptoduct 51",
                            Name = "Product 51",
                            Price = 218m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for ptoduct 52",
                            Name = "Product 52",
                            Price = 874m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for ptoduct 53",
                            Name = "Product 53",
                            Price = 415m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for ptoduct 54",
                            Name = "Product 54",
                            Price = 330m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for ptoduct 55",
                            Name = "Product 55",
                            Price = 570m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for ptoduct 56",
                            Name = "Product 56",
                            Price = 213m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for ptoduct 57",
                            Name = "Product 57",
                            Price = 664m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for ptoduct 58",
                            Name = "Product 58",
                            Price = 951m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for ptoduct 59",
                            Name = "Product 59",
                            Price = 222m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for ptoduct 60",
                            Name = "Product 60",
                            Price = 248m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for ptoduct 61",
                            Name = "Product 61",
                            Price = 548m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for ptoduct 62",
                            Name = "Product 62",
                            Price = 633m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for ptoduct 63",
                            Name = "Product 63",
                            Price = 424m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for ptoduct 64",
                            Name = "Product 64",
                            Price = 605m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for ptoduct 65",
                            Name = "Product 65",
                            Price = 424m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for ptoduct 66",
                            Name = "Product 66",
                            Price = 964m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for ptoduct 67",
                            Name = "Product 67",
                            Price = 378m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for ptoduct 68",
                            Name = "Product 68",
                            Price = 703m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for ptoduct 69",
                            Name = "Product 69",
                            Price = 705m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for ptoduct 70",
                            Name = "Product 70",
                            Price = 507m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for ptoduct 71",
                            Name = "Product 71",
                            Price = 628m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for ptoduct 72",
                            Name = "Product 72",
                            Price = 902m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for ptoduct 73",
                            Name = "Product 73",
                            Price = 773m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for ptoduct 74",
                            Name = "Product 74",
                            Price = 982m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for ptoduct 75",
                            Name = "Product 75",
                            Price = 870m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for ptoduct 76",
                            Name = "Product 76",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for ptoduct 77",
                            Name = "Product 77",
                            Price = 391m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for ptoduct 78",
                            Name = "Product 78",
                            Price = 543m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for ptoduct 79",
                            Name = "Product 79",
                            Price = 905m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for ptoduct 80",
                            Name = "Product 80",
                            Price = 224m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for ptoduct 81",
                            Name = "Product 81",
                            Price = 650m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for ptoduct 82",
                            Name = "Product 82",
                            Price = 124m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for ptoduct 83",
                            Name = "Product 83",
                            Price = 863m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for ptoduct 84",
                            Name = "Product 84",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for ptoduct 85",
                            Name = "Product 85",
                            Price = 658m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for ptoduct 86",
                            Name = "Product 86",
                            Price = 628m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for ptoduct 87",
                            Name = "Product 87",
                            Price = 865m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for ptoduct 88",
                            Name = "Product 88",
                            Price = 635m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for ptoduct 89",
                            Name = "Product 89",
                            Price = 321m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for ptoduct 90",
                            Name = "Product 90",
                            Price = 874m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for ptoduct 91",
                            Name = "Product 91",
                            Price = 169m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for ptoduct 92",
                            Name = "Product 92",
                            Price = 703m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for ptoduct 93",
                            Name = "Product 93",
                            Price = 526m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for ptoduct 94",
                            Name = "Product 94",
                            Price = 787m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for ptoduct 95",
                            Name = "Product 95",
                            Price = 531m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for ptoduct 96",
                            Name = "Product 96",
                            Price = 446m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for ptoduct 97",
                            Name = "Product 97",
                            Price = 283m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for ptoduct 98",
                            Name = "Product 98",
                            Price = 460m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for ptoduct 99",
                            Name = "Product 99",
                            Price = 624m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProducInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProducInStockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProducInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProducInStockId = 1,
                            ProductId = 1,
                            Stock = 12
                        },
                        new
                        {
                            ProducInStockId = 2,
                            ProductId = 2,
                            Stock = 12
                        },
                        new
                        {
                            ProducInStockId = 3,
                            ProductId = 3,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 4,
                            ProductId = 4,
                            Stock = 13
                        },
                        new
                        {
                            ProducInStockId = 5,
                            ProductId = 5,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 6,
                            ProductId = 6,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 7,
                            ProductId = 7,
                            Stock = 18
                        },
                        new
                        {
                            ProducInStockId = 8,
                            ProductId = 8,
                            Stock = 9
                        },
                        new
                        {
                            ProducInStockId = 9,
                            ProductId = 9,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 10,
                            ProductId = 10,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 11,
                            ProductId = 11,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 12,
                            ProductId = 12,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 13,
                            ProductId = 13,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 14,
                            ProductId = 14,
                            Stock = 6
                        },
                        new
                        {
                            ProducInStockId = 15,
                            ProductId = 15,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 16,
                            ProductId = 16,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 17,
                            ProductId = 17,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 18,
                            ProductId = 18,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 19,
                            ProductId = 19,
                            Stock = 6
                        },
                        new
                        {
                            ProducInStockId = 20,
                            ProductId = 20,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 21,
                            ProductId = 21,
                            Stock = 18
                        },
                        new
                        {
                            ProducInStockId = 22,
                            ProductId = 22,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 23,
                            ProductId = 23,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 24,
                            ProductId = 24,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 25,
                            ProductId = 25,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 26,
                            ProductId = 26,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 27,
                            ProductId = 27,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 28,
                            ProductId = 28,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 29,
                            ProductId = 29,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 30,
                            ProductId = 30,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 31,
                            ProductId = 31,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 32,
                            ProductId = 32,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 33,
                            ProductId = 33,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 34,
                            ProductId = 34,
                            Stock = 3
                        },
                        new
                        {
                            ProducInStockId = 35,
                            ProductId = 35,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 36,
                            ProductId = 36,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 37,
                            ProductId = 37,
                            Stock = 12
                        },
                        new
                        {
                            ProducInStockId = 38,
                            ProductId = 38,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 39,
                            ProductId = 39,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 40,
                            ProductId = 40,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 41,
                            ProductId = 41,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 42,
                            ProductId = 42,
                            Stock = 13
                        },
                        new
                        {
                            ProducInStockId = 43,
                            ProductId = 43,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 44,
                            ProductId = 44,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 45,
                            ProductId = 45,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 46,
                            ProductId = 46,
                            Stock = 0
                        },
                        new
                        {
                            ProducInStockId = 47,
                            ProductId = 47,
                            Stock = 1
                        },
                        new
                        {
                            ProducInStockId = 48,
                            ProductId = 48,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 49,
                            ProductId = 49,
                            Stock = 1
                        },
                        new
                        {
                            ProducInStockId = 50,
                            ProductId = 50,
                            Stock = 5
                        },
                        new
                        {
                            ProducInStockId = 51,
                            ProductId = 51,
                            Stock = 4
                        },
                        new
                        {
                            ProducInStockId = 52,
                            ProductId = 52,
                            Stock = 5
                        },
                        new
                        {
                            ProducInStockId = 53,
                            ProductId = 53,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 54,
                            ProductId = 54,
                            Stock = 9
                        },
                        new
                        {
                            ProducInStockId = 55,
                            ProductId = 55,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 56,
                            ProductId = 56,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 57,
                            ProductId = 57,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 58,
                            ProductId = 58,
                            Stock = 15
                        },
                        new
                        {
                            ProducInStockId = 59,
                            ProductId = 59,
                            Stock = 1
                        },
                        new
                        {
                            ProducInStockId = 60,
                            ProductId = 60,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 61,
                            ProductId = 61,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 62,
                            ProductId = 62,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 63,
                            ProductId = 63,
                            Stock = 2
                        },
                        new
                        {
                            ProducInStockId = 64,
                            ProductId = 64,
                            Stock = 4
                        },
                        new
                        {
                            ProducInStockId = 65,
                            ProductId = 65,
                            Stock = 1
                        },
                        new
                        {
                            ProducInStockId = 66,
                            ProductId = 66,
                            Stock = 0
                        },
                        new
                        {
                            ProducInStockId = 67,
                            ProductId = 67,
                            Stock = 2
                        },
                        new
                        {
                            ProducInStockId = 68,
                            ProductId = 68,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 69,
                            ProductId = 69,
                            Stock = 15
                        },
                        new
                        {
                            ProducInStockId = 70,
                            ProductId = 70,
                            Stock = 5
                        },
                        new
                        {
                            ProducInStockId = 71,
                            ProductId = 71,
                            Stock = 16
                        },
                        new
                        {
                            ProducInStockId = 72,
                            ProductId = 72,
                            Stock = 12
                        },
                        new
                        {
                            ProducInStockId = 73,
                            ProductId = 73,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 74,
                            ProductId = 74,
                            Stock = 14
                        },
                        new
                        {
                            ProducInStockId = 75,
                            ProductId = 75,
                            Stock = 15
                        },
                        new
                        {
                            ProducInStockId = 76,
                            ProductId = 76,
                            Stock = 6
                        },
                        new
                        {
                            ProducInStockId = 77,
                            ProductId = 77,
                            Stock = 12
                        },
                        new
                        {
                            ProducInStockId = 78,
                            ProductId = 78,
                            Stock = 18
                        },
                        new
                        {
                            ProducInStockId = 79,
                            ProductId = 79,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 80,
                            ProductId = 80,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 81,
                            ProductId = 81,
                            Stock = 8
                        },
                        new
                        {
                            ProducInStockId = 82,
                            ProductId = 82,
                            Stock = 15
                        },
                        new
                        {
                            ProducInStockId = 83,
                            ProductId = 83,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 84,
                            ProductId = 84,
                            Stock = 18
                        },
                        new
                        {
                            ProducInStockId = 85,
                            ProductId = 85,
                            Stock = 18
                        },
                        new
                        {
                            ProducInStockId = 86,
                            ProductId = 86,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 87,
                            ProductId = 87,
                            Stock = 2
                        },
                        new
                        {
                            ProducInStockId = 88,
                            ProductId = 88,
                            Stock = 2
                        },
                        new
                        {
                            ProducInStockId = 89,
                            ProductId = 89,
                            Stock = 19
                        },
                        new
                        {
                            ProducInStockId = 90,
                            ProductId = 90,
                            Stock = 17
                        },
                        new
                        {
                            ProducInStockId = 91,
                            ProductId = 91,
                            Stock = 10
                        },
                        new
                        {
                            ProducInStockId = 92,
                            ProductId = 92,
                            Stock = 9
                        },
                        new
                        {
                            ProducInStockId = 93,
                            ProductId = 93,
                            Stock = 9
                        },
                        new
                        {
                            ProducInStockId = 94,
                            ProductId = 94,
                            Stock = 11
                        },
                        new
                        {
                            ProducInStockId = 95,
                            ProductId = 95,
                            Stock = 0
                        },
                        new
                        {
                            ProducInStockId = 96,
                            ProductId = 96,
                            Stock = 6
                        },
                        new
                        {
                            ProducInStockId = 97,
                            ProductId = 97,
                            Stock = 5
                        },
                        new
                        {
                            ProducInStockId = 98,
                            ProductId = 98,
                            Stock = 7
                        },
                        new
                        {
                            ProducInStockId = 99,
                            ProductId = 99,
                            Stock = 16
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
